Added date functionality.
Highshirt99/todo_app pull request #3
Opened 2023-06-25 21:49 UTC by Highshirt99

2023-06-26 07:47 UTC, codarbind requested changes

2023-06-26 07:47 UTC, codarbind commented on src/reduxStore/todoSlice.js
> +      const dateCreated = `${day}/${month}/${year}`;
rename `dateCreated` to `created_at`

2023-06-26 07:47 UTC, codarbind commented on src/reduxStore/todoSlice.js
> +      const dateCreated = `${day}/${month}/${year}`;
also add `completed_at`

2023-06-26 07:47 UTC, codarbind commented on src/components/TodoList.js
> +              <p>{item.title}</p>
I dont think this is semantic

could there be a better tag/element to use instead of `<p>`?

2023-06-26 07:47 UTC, codarbind commented on src/components/TodoList.js
> +              <p>{item.title}</p>
where would we place/show date of completion?

I think there could be a little not too tiny bar under each todo that could show date of creation and date of completion and perhaps other similar details

let me know which arrangement you want to go with befoe implementation

well done

2023-06-26 07:58 UTC, codarbind commented on src/reduxStore/todoSlice.js
> +      const dateCreated = `${day}/${month}/${year}`;
<img width="308" alt="image" src="https://github.com/Highshirt99/TODOTODAY/assets/53216981/23864d71-229d-4e6d-9832-192cd9bbae56">

2023-06-26 07:59 UTC, codarbind commented on src/components/TodoList.js
> +              <p>{item.title}</p>
something like the position where the due date  is here

<img width="308" alt="image" src="https://github.com/Highshirt99/TODOTODAY/assets/53216981/d8271b84-67e5-4676-809e-58f5535154d2">

2023-06-26 08:22 UTC, Highshirt99 commented
All reviews would be made later today. I'm currently at my IT placement.

On Mon, Jun 26, 2023, 8:59 AM ADEKOLA Abdwahab ***@***.***>
wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In src/components/TodoList.js
> <https://github.com/Highshirt99/TODOTODAY/pull/3#discussion_r1241782167>:
>
> > @@ -75,7 +75,10 @@ function TodoList() {
>                    <img src={check} alt="" />
>                  ) : null}
>                </div>
> -              {item.title}
> +              <p>{item.title}</p>
>
> something like the position where the due date is here
> [image: image]
> <https://user-images.githubusercontent.com/53216981/248723790-d8271b84-67e5-4676-809e-58f5535154d2.png>
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Highshirt99/TODOTODAY/pull/3#discussion_r1241782167>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AW2CBSMEQG5ZNHP4EAQYUBTXNE6NJANCNFSM6AAAAAAZTMKCA4>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2023-07-05 13:21 UTC, mo-renike commented
It is best to add a snapshot of your frontend work to your PR. 
Or host your branch for testing

2023-07-05 13:25 UTC, Highshirt99 commented
There's a link to preview each PR made.

On Wed, Jul 5, 2023, 2:22 PM Morenike Oyewole ***@***.***>
wrote:

> It is best to add a snapshot of your frontend work to your PR.
> Or host your branch for testing
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Highshirt99/TODOTODAY/pull/3#issuecomment-1621747859>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AW2CBSPWLW6SRFDDX2LD2TLXOVS7RANCNFSM6AAAAAAZTMKCA4>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2023-07-05 13:28 UTC, mo-renike approved these changes

2023-07-08 04:30 UTC, codarbind approved these changes

2023-07-08 04:30 UTC, merged